In [67]:
import numpy as np
import pandas as pd
import regex 
import unicodedata
import matplotlib as plt

In [41]:
total_df = pd.read_csv(r"data\all_data.csv")
total_score_df = pd.read_csv('data/all_data_scores.csv', lineterminator = "\n")
cols_sentences = ['Upside_Review', 'Downside_Review']
cols_score_sentences =['Upside_Review', 'Downside_Review', "text"]
# total_df.head()

In [24]:
# punctuation symbols and space
PUNC_SYS = regex.compile(r"[\p{P}\p{S}]")
SPACES = regex.compile(r"\s+")

def punct_clean(text):
    text = unicodedata.normalize("NFKC", text)
    text = PUNC_SYS.sub(" ", text)
    text = SPACES.sub(" ", text)
    return text.strip()

In [42]:
test = total_df[cols_sentences].iloc[:5]
test.head(3)

,Upside_Review,Downside_Review
0,性价比超高的酒店，虽然价格比较贵，但是享受到的服务环境都还不错。,NaN
1,奥斯曼风格的建筑很有特色，房间装修精致，距离安卡拉城堡非常近，附近餐厅多，纪念品小商店多,不知道是不是因为夏季的原因，房间的空调不太给力，房间热；酒店员工会在窗外聊天，不考虑客人是不...
2,非常喜歡酒店的環境氛圍，特別是通過地下通道到達博物館，這是一個驚喜（但入住時酒店服務人員并未...,酒店的空調令人傷心，第一天房間空調不起作用，次日上午出門時告知酒店經理，回來后依然沒有處理，...

In [43]:
test = total_df[cols_sentences].iloc[:5]
test[cols_sentences] = test[cols_sentences].map(punct_clean, na_action ='ignore')
test.head()

,Upside_Review,Downside_Review
0,性价比超高的酒店 虽然价格比较贵 但是享受到的服务环境都还不错,NaN
1,奥斯曼风格的建筑很有特色 房间装修精致 距离安卡拉城堡非常近 附近餐厅多 纪念品小商店多,不知道是不是因为夏季的原因 房间的空调不太给力 房间热 酒店员工会在窗外聊天 不考虑客人是不...
2,非常喜歡酒店的環境氛圍 特別是通過地下通道到達博物館 這是一個驚喜 但入住時酒店服務人員并未...,酒店的空調令人傷心 第一天房間空調不起作用 次日上午出門時告知酒店經理 回來后依然沒有處理 ...
3,NaN,冷氣每隔5 15分鐘就會自動關閉 重新開啟有時候也要按三次才會開啟 飯店人員並沒有很積極地幫...
4,雖因為疫情影響加上老牌酒店旅客很少 但五星級的風骨猶存 這是寶藏好好傳承 比新酒店服務不到位強百倍,NaN

In [44]:
total_df[cols_sentences] = total_df[cols_sentences].map(punct_clean, na_action = 'ignore')
total_df.head(2)

,Unnamed: 0,Review_Language,City Name,Hotel Name,Upside_Review,Downside_Review,Review_Score,Sentiment,source,Prompt_Language,na_up_review,na_down_review
0,0,Chinese,Ankara,迪万卡拉汉酒店,性价比超高的酒店 虽然价格比较贵 但是享受到的服务环境都还不错,NaN,10.0,POS,0,NaN,False,True
1,1,Chinese,Ankara,迪万卡拉汉酒店,奥斯曼风格的建筑很有特色 房间装修精致 距离安卡拉城堡非常近 附近餐厅多 纪念品小商店多,不知道是不是因为夏季的原因 房间的空调不太给力 房间热 酒店员工会在窗外聊天 不考虑客人是不...,4.0,NEG,0,NaN,False,False

In [57]:
total_score_df[cols_score_sentences] = total_score_df[cols_score_sentences].map(punct_clean, na_action = 'ignore')

In [53]:
total_df.shape

(19985, 12)

In [54]:
total_df.isnull().sum()

Unnamed: 0            0
Review_Language       0
City Name             0
Hotel Name            0
Upside_Review       997
Downside_Review    2195
Review_Score          0
Sentiment             0
source                0
Prompt_Language    9985
na_up_review          0
na_down_review        0
dtype: int64

In [66]:
total_df.isnull().sum()

Unnamed: 0            0
Review_Language       0
City Name             0
Hotel Name            0
Upside_Review       997
Downside_Review    2195
Review_Score          0
Sentiment             0
source                0
Prompt_Language    9985
na_up_review          0
na_down_review        0
dtype: int64

In [55]:
total_score_df.shape

(19985, 14)

In [56]:
total_score_df.isnull().sum()

Unnamed: 0            0
Review_Language       0
City Name             0
Hotel Name            0
Upside_Review      1023
Downside_Review    2240
Review_Score          0
Sentiment             0
Analytic              0
source                0
Prompt_Language    9985
text                  0
Readability        5985
Descriptiveness       0
dtype: int64

# Not sure what to assing for empty Readability value

In [65]:
score_check = total_score_df[["Upside_Review", "Downside_Review", 'Readability']]
a = score_check[~score_check['Readability'].isnull()].max()
a

Upside_Review      шторки на кроватях номер просторный и приятный...
Downside_Review    я не знаю почему но учитывая то что отель бере...
Readability                                                 120.7125
dtype: object

In [ ]:
r_missing = total_score_df["Readability"].isna()

for col in ["Upside_Review", "Downside_Review", "Prompt_Language"]:
    both = (r_missing & total_score_df[col].isna()).sum()
    print(f"{col}: {both} of {r_missing.sum()} Readability-NaN rows are also NaN here")

# Rows where Readability is NaN but both reviews exist
has_text = total_score_df["Upside_Review"].notna() | total_score_df["Downside_Review"].notna()
print((r_missing & has_text).sum())


print(total_score_df.loc[r_missing, "Prompt_Language"].value_counts(dropna=False).head(10))#language breakdown of the missing rows

Upside_Review: 379 of 5985 Readability-NaN rows are also NaN here
Downside_Review: 584 of 5985 Readability-NaN rows are also NaN here
Prompt_Language: 2985 of 5985 Readability-NaN rows are also NaN here
5985
Prompt_Language
NaN                  2985
English(Korean)       191
English(Italian)      181
Italian               178
English(German)       174
English(Romanian)     174
Korean                170
Spanish               166
English(Spanish)      166
Turkish               165
Name: count, dtype: int64